--- # file: site.yml
- hosts: test-servers

  #remote_user: root

  gather_facts: False

  tasks:
    - { include: included.yml, remote_user: root }

    - { include: included.yml, ansible_ssh_user: lxruser }

