--- # file: site.yml
- hosts: test-servers

  vars: 
    testvar1: "{{ ansible_default_ipv4 }}"

  gather_facts: False
  #gather_facts: True

  tasks:

    # Facts
    - debug: var=ansible_hostname
    - debug: var=ansible_default_ipv4

    # Magic variables
    - debug: var=hostvars
    - debug: var=group_names
    - debug: var=groups
    - debug: var=environment
    - debug: var=inventory_hostname
    - debug: var=inventory_hostname_short
    - debug: var=play_hosts
    - debug: var=inventory_dir
    - debug: var=inventory_file

