--- # Setup the login environment of lxruser
- hosts: lxrservers

  vars:
    lxr_user: 'lxruser'

    install_dir: ~/local
    share_dir: ~/local/share

  remote_user: "{{ lxr_user }}"
  gather_facts: False

  tasks:

    - name: create the install directory for glimpse
      file: path={{ install_dir }} state=directory mode=0755

    - name: create the directory for the glimpse index
      file: path={{ share_dir }}/glimpse state=directory mode=0755

    - name: create the directory for Lxr DB and the source trees 
      file: path={{ share_dir }}/lxr state=directory mode=0755

    - name: expand install directory to obtain the absolute path
      command: chdir={{ install_dir }} pwd
      register: install_dir_full
      changed_when: False

    - name: setup $PATH for bash login usage
      lineinfile:
        "dest=~/.bash_profile
        regexp='^PATH=' line='PATH=$PATH:{{ install_dir_full.stdout }}/bin'
        state=present"

