--- # Install glimpse by lxr_user
- hosts: lxrservers

  # Glimpse requires a proper license to use. See the below:
  #   http://webglimpse.net/sublicensing/licensing.html
  #   http://webglimpse.net/download.php
 
  vars:
    lxr_user: 'lxruser'

    lxr_glimpse_bin: '/home/lxruser/local/bin/glimpse'

    tarball: ~/glimpse-latest.tar.gz
    download_url: "http://webglimpse.net/trial/glimpse-latest.tar.gz"
    csum: "3045296877bc7a3714ae10872056030175c2f10de83544aa7f08811f24d38077"

  remote_user: "{{ lxr_user }}"
  gather_facts: False

  tasks:

    - name: check if glimpse binary exists
      stat: path={{ lxr_glimpse_bin }}
      register: st

    - name: notice about glimpse-latest.tar.gz
      debug: msg="If the remote tarball is changed,
                  sha256sum(csum) must be updated by hand."

    - name: download the tarball
      get_url: url={{ download_url }}
        sha256sum={{ csum }} dest={{ tarball }} force=True
      register: download

    - include: ./build_install_tarball.yml
      vars:
        build_dir: ~/glimpse
        install_dir: ~/local
        sudo_install: False
      when: "{{ st.stat.exists == False or st.stat.size == 0 or
                download | changed }}"

